from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from app.config import settings

DATA_DIR = settings.base_dir / "data" / "worldbank"

# World Bank indicator metadata — exact content from World Bank DataBank Metadata Glossary
INDICATORS: Dict[str, Dict[str, str]] = {
    "gdp": {
        "code": "NY.GDP.MKTP.KD.ZG",
        "label": "GDP (annual % growth)",
        "file": "gdp.json",
        "topic": "Economic Policy & Debt: National accounts: Growth rates",
        "dataset": "WB_WDI",
        "unit": "%",
        "periodicity": "Annual",
        "reference_period": "1961-2024",
        "aggregation_method": "Weighted average",
        "source": "Country official statistics, National Statistical Organizations and/or Central Banks; National Accounts data files, Organisation for Economic Co-operation and Development (OECD); Staff estimates, World Bank (WB)",
        "long_definition": (
            "Gross domestic product is the total income earned through the production of goods and services "
            "in an economic territory during an accounting period. It can be measured in three different ways: "
            "using either the expenditure approach, the income approach, or the production approach. This "
            "indicator denotes the percentage change over each previous year of the constant price (base year "
            "2015) series in United States dollars."
        ),
        "statistical_concept": (
            "National accounts are compiled in accordance with international standards: System of National "
            "Accounts, 2008 or 1993 versions. The conceptual elements of the SNA measure what takes place in "
            "the economy, between which agents, and for what purpose. At the heart of the SNA is the production "
            "of goods and services. In simple terms, the amount of value added generated by production represents "
            "GDP. The income corresponding to GDP is distributed to various agents as income, and it is the "
            "process of distributing and redistributing income that allows one agent to consume the goods and "
            "services produced by another agent or to acquire goods and services for later consumption."
        ),
        "development_relevance": (
            "National accounts are critical for understanding and managing a country's economy. They provide a "
            "framework for the analysis of economic performance and are the basis for estimating GDP and GNI, "
            "the most widely used indicators of economic performance. They are essential for government "
            "policymakers providing data needed to design and assess fiscal and monetary policies, and are used "
            "by businesses and investors to assess the economic climate. GDP aggregates provide a snapshot of "
            "the size and health of an economy by measuring total economic activity within a country. They allow "
            "comparisons between different economies, useful for trade negotiations, investment decisions, and "
            "economic benchmarking. By examining aggregates over time, economists and analysts can identify "
            "trends, cycles, and potential areas of concern within an economy."
        ),
        "limitations": (
            "Each industry's contribution to growth is measured by growth in the industry's value added. "
            "Value added in constant prices can in principle be estimated by measuring the quantity of goods "
            "and services produced, valuing them at base year prices, and subtracting the cost of intermediate "
            "inputs. This double-deflation method requires detailed price structure information. In many "
            "industries, value added is extrapolated using single volume indexes. Particularly in services, "
            "value added in constant prices is often imputed from labor inputs. Informal economic activities "
            "pose a particular measurement problem, especially in developing countries. Rebasing of national "
            "accounts can alter measured growth rates and lead to breaks in series that affect consistency over "
            "time. The World Bank rescales GDP to a common reference year; because rescaling changes implicit "
            "weights in regional aggregates, aggregate growth rates are not comparable across editions with "
            "different base years."
        ),
        "license": "CC BY-4.0",
        "description": (
            "GDP (annual % growth) measures the percentage change over each previous year of the constant-price "
            "(base year 2015) GDP series in US dollars. GDP is the total income earned through the production of "
            "goods and services in an economic territory during an accounting period, measurable via the "
            "expenditure, income, or production approach. National accounts follow the System of National "
            "Accounts (SNA 2008/1993). GDP aggregates provide a snapshot of an economy's size and health, "
            "support fiscal and monetary policy design, and enable cross-country comparisons for trade, "
            "investment, and benchmarking. Reference period: 1961–2024. Source: national statistical "
            "organizations, OECD, World Bank staff estimates. License: CC BY-4.0."
        ),
    },
    "co2": {
        "code": "EN.ATM.CO2E.KT",
        "label": "CO₂ Emissions (kt)",
        "file": "co2.json",
        "topic": "Environment: Emissions",
        "unit": "kt (kiloton)",
        "periodicity": "Annual",
        "aggregation_method": "Gap-filled total",
        "source": "Climate Watch Historical GHG Emissions (1990-2020). 2023. Washington, DC: World Resources Institute. Available online at: https://www.climatewatchdata.org/ghg-emissions",
        "long_definition": (
            "Carbon dioxide emissions are those stemming from the burning of fossil fuels and the manufacture "
            "of cement. They include carbon dioxide produced during consumption of solid, liquid, and gas fuels "
            "and gas flaring."
        ),
        "statistical_concept": (
            "Carbon dioxide emissions, largely by-products of energy production and use, account for the "
            "largest share of greenhouse gases associated with global warming. Anthropogenic CO2 emissions "
            "result primarily from fossil fuel combustion and cement manufacturing. Oil releases about 50% more "
            "CO2 than natural gas, and coal releases about twice as much. Cement manufacturing releases about "
            "half a metric ton of CO2 per metric ton of cement produced. Data includes gases from burning of "
            "fossil fuels and cement manufacture but excludes emissions from land use such as deforestation. "
            "The unit of measurement is kt (kiloton). CO2 emissions are often calculated as elemental carbon "
            "and converted to CO2 mass by multiplying by 3.667 (ratio of mass of carbon dioxide to carbon)."
        ),
        "development_relevance": (
            "CO2 is a naturally occurring gas fixed by photosynthesis into organic matter and a byproduct of "
            "fossil fuel combustion and biomass burning. It is the principal anthropogenic greenhouse gas "
            "affecting the Earth's radiative balance and the reference gas (Global Warming Potential of 1) "
            "against which other greenhouse gases are measured. Burning of carbon-based fuels since the "
            "industrial revolution has rapidly increased atmospheric CO2 concentrations, causing anthropogenic "
            "climate change and ocean acidification. Emission intensity is the average emission rate of a given "
            "pollutant relative to the intensity of a specific activity. The Kyoto Protocol (1997) works toward "
            "curbing CO2 emissions globally. For a complete picture of a country's climate influence, methane "
            "and nitrous oxide should also be considered, particularly in agricultural economies."
        ),
        "limitations": (
            "This series excludes Land-use Change & Forestry (LUCF). World totals include international bunker "
            "fuel-related emissions and emissions from territories not part of the UNFCCC."
        ),
        "license": "Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)",
        "description": (
            "CO2 emissions (kt) measures carbon dioxide emissions from burning fossil fuels and cement "
            "manufacture, including CO2 from solid, liquid, and gas fuel consumption and gas flaring. "
            "Excludes land-use change and forestry. CO2 is the principal anthropogenic greenhouse gas "
            "(Global Warming Potential = 1) driving global warming and ocean acidification. Measured in "
            "kilotons; emissions are converted from elemental carbon using a factor of 3.667. Source: "
            "Climate Watch / World Resources Institute (1990–2020). License: CC BY-NC 4.0."
        ),
    },
    "agri_land": {
        "code": "AG.LND.AGRI.ZS",
        "label": "Agricultural Land (% of land area)",
        "file": "agri_land.json",
        "topic": "Environment: Land use",
        "dataset": "WB_WDI",
        "unit": "% (share) of land area",
        "periodicity": "Annual",
        "reference_period": "1961-2023",
        "aggregation_method": "Weighted average",
        "source": "FAO electronic files and web site, Food and Agriculture Organization of the United Nations (FAO)",
        "long_definition": (
            "Agricultural land refers to the share of land area that is arable, under permanent crops, and "
            "under permanent pastures. Arable land includes land defined by the FAO as land under temporary "
            "crops (double-cropped areas are counted once), temporary meadows for mowing or for pasture, land "
            "under market or kitchen gardens, and land temporarily fallow. Land abandoned as a result of "
            "shifting cultivation is excluded. Land under permanent crops is land cultivated with crops that "
            "occupy the land for long periods and need not be replanted after each harvest, such as cocoa, "
            "coffee, and rubber. This category includes land under flowering shrubs, fruit trees, nut trees, "
            "and vines, but excludes land under trees grown for wood or timber. Permanent pasture is land used "
            "for five or more years for forage, including natural and cultivated crops."
        ),
        "statistical_concept": (
            "Agriculture is still a major sector in many economies, providing developing countries with food "
            "and revenue but also potentially degrading natural resources. Poor farming practices can cause "
            "soil erosion and loss of fertility. Excessive use of chemical fertilizers can alter soil chemistry. "
            "Salinization of irrigated land diminishes soil fertility. Agricultural land is also classified as "
            "irrigated and non-irrigated. In arid and semi-arid countries agriculture is often confined to "
            "irrigated land. Data on agricultural land are valuable for studying agricultural production, food "
            "security, and cropping intensity. Total land area does not include inland water bodies such as "
            "major rivers and lakes. Variations from year to year may be due to updated or revised data rather "
            "than to change in area."
        ),
        "development_relevance": (
            "Agricultural land covers more than one-third of the world's land area, with arable land "
            "representing less than one-third of agricultural land (about 10% of the world's land area). "
            "FAO's agricultural land data supports understanding of a country's agricultural sector structure, "
            "food security policy planning, environmental indicators including investment in agriculture, and "
            "gross/net crop area data useful for policy formulation and monitoring. The appropriate mix of "
            "inputs depends on local climate, land quality, and economic development."
        ),
        "limitations": (
            "Data are collected by FAO from official national sources through annual questionnaires and "
            "supplemented with secondary data sources. The FAO tries to impose standard definitions and "
            "reporting methods, but complete consistency across countries and over time is not possible. "
            "Permanent pastures are quite different in nature in African vs. dry Middle Eastern countries. "
            "Agricultural employment data should be used with caution as much is informal and unrecorded, "
            "including substantial work performed by women and children. Areas of former states are included "
            "in successor states."
        ),
        "license": "CC BY-4.0",
        "description": (
            "Agricultural land (% of land area) measures the share of land that is arable, under permanent "
            "crops, or under permanent pastures. Arable land covers temporary crops, temporary meadows, "
            "kitchen gardens, and temporarily fallow land. Permanent crops include cocoa, coffee, rubber, "
            "fruit trees, and vines. Permanent pastures are used five or more years for forage. Agricultural "
            "land covers over one-third of the world's total land area. Data collected by FAO from national "
            "sources annually. Reference period: 1961–2023. Source: FAO. License: CC BY-4.0."
        ),
    },
}

# Keywords mapped to indicator keys
_KEYWORD_MAP: List[Tuple[List[str], str]] = [
    (["gdp", "gross domestic product", "economic growth", "economy"], "gdp"),
    (["co2", "carbon", "emission", "greenhouse", "ghg"], "co2"),
    (["agricultural land", "agriculture land", "farming land", "land use", "agri land", "agriland", "cropland", "agri"], "agri_land"),
]


def detect_indicators(question: str) -> List[str]:
    """Return indicator keys relevant to the question."""
    q = question.lower()
    matched: List[str] = []
    for keywords, key in _KEYWORD_MAP:
        for kw in keywords:
            if kw in q:
                if key not in matched:
                    matched.append(key)
                break
    return matched





def fetch_indicator(key: str) -> Tuple[Dict[str, str], List[Dict[str, Any]]]:
    """Load indicator data from local JSON file."""
    info = INDICATORS[key]
    json_path = DATA_DIR / info["file"]

    if not json_path.exists():
        return info, []

    payload = json.loads(json_path.read_text(encoding="utf-8"))

    if not isinstance(payload, list) or len(payload) < 2:
        return info, []

    raw_points = payload[1] or []
    data_points: List[Dict[str, Any]] = []
    for entry in raw_points:
        year = entry.get("date")
        value = entry.get("value")
        if year and value is not None:
            data_points.append({"label": str(year), "value": round(float(value), 4)})

    data_points.sort(key=lambda d: d["label"])
    return info, data_points


def build_worldbank_context(indicator_keys: List[str]) -> str:
    """Fetch data for requested indicators and return a text context string.

    All available data points are included so the LLM can decide which
    years/points to use for the answer and optional chart.
    """
    if not indicator_keys:
        return ""

    text_parts: List[str] = []

    for key in indicator_keys:
        info, points = fetch_indicator(key)

        meta_lines = [
            f"## {info['label']} (Code: {info['code']})",
            f"Topic: {info.get('topic', 'N/A')} | Unit: {info.get('unit', 'N/A')} | Periodicity: {info.get('periodicity', 'Annual')}",
            f"Reference period: {info.get('reference_period', 'N/A')} | Aggregation: {info.get('aggregation_method', 'N/A')}",
            f"Source: {info.get('source', 'World Bank')}",
            f"Definition: {info.get('long_definition', info.get('description', ''))}",
        ]
        if info.get('statistical_concept'):
            meta_lines.append(f"Methodology: {info['statistical_concept']}")
        if info.get('development_relevance'):
            meta_lines.append(f"Development relevance: {info['development_relevance']}")
        if info.get('limitations'):
            meta_lines.append(f"Limitations: {info['limitations']}")
        meta_lines.append(f"License: {info.get('license', 'CC BY-4.0')}")

        meta_header = "\n".join(meta_lines)

        if not points:
            text_parts.append(f"{meta_header}\nData: No data available.")
            continue

        rows = [f"  {p['label']}: {p['value']}" for p in points]
        range_label = f"{points[0]['label']}–{points[-1]['label']}"
        text_parts.append(f"{meta_header}\nAll data ({range_label}, {len(rows)} points):\n" + "\n".join(rows))

    return "\n\n".join(text_parts)
